name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: ${{ secrets.SSH_HOST_NGINX }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY_NGINX }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: ${{ secrets.NGINX_ENDPOINT_RUNNER }}
          append: |
            - endpoint: ${{ secrets.NGINX_ENDPOINT_ARM64 }}
              platforms: linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push (Nginx With ngx_cache_purge Module)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            navystack/nginx-ngx_cache_purge:dev
            navystack/nginx-ngx_cache_purge:mainline
            navystack/nginx-ngx_cache_purge:1.25.3
            navystack/nginx-ngx_cache_purge:latest
          platforms: |
            linux/amd64
            linux/arm64
          #cache-from: ${{ secrets.BUILD_CACHE_FROM }}
          #cache-to: ${{ secrets.BUILD_CACHE_TO }}
      - name: Clear cache
        uses: actions/github-script@v6
        with:
          script: |
            console.log("About to clear")
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              console.log(cache)
              github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id,
              })
            }
            console.log("Clear completed")
